apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend
  labels:
    app: guestbook-backend
spec:
  selector:
    app: guestbook-backend
  ports:
  - port: 80
    targetPort: 3000
    name: web
