apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook-ui
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  endpoints:
  - port: web