apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook-backend
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: guestbook-backend
  endpoints:
  - port: web