apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: guestbook
  namespace: monitoring
spec:
  # serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false