apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: guestbook
  namespace: monitoring
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      team: backend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false